# Generated by Django 3.0.4 on 2020-03-13 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyTest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='gboynum',
            field=models.IntegerField(verbose_name='男生数量'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='gdate',
            field=models.DateTimeField(verbose_name='开班日期'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='ggirlnum',
            field=models.IntegerField(verbose_name='女生数量'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='gname',
            field=models.CharField(max_length=10, verbose_name='班级名称'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='isDelete',
            field=models.BooleanField(verbose_name='删除'),
        ),
        migrations.AlterField(
            model_name='student',
            name='isDelete',
            field=models.BooleanField(default=False, verbose_name='删除'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sage',
            field=models.IntegerField(verbose_name='学生年龄'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sgender',
            field=models.BooleanField(default=True, verbose_name='学生性别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sgrade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyTest.Grade', verbose_name='学生所属班级'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sinfo',
            field=models.CharField(max_length=64, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sname',
            field=models.CharField(max_length=20, verbose_name='学生姓名'),
        ),
    ]
